UpdaterLaunched = "Welcome to the updater, we are starting things up, please do not close this window!"
UpdateBC = "Updater is updating the randomizer core";
UpdateBCDone = "Updater has updated the randomizer core";
UpdateSprites = "Updater is updating the randomizer sprites";
UpdateSpriteDone = "Updater has updated the randomizer sprites";
UpdaterCompleted = "Update completed all update tasks!"
UpdaterClosing = "Launching Beyond Chaos"
UpdaterBCError = "BeyondChaos.zip does not exist, if this an error please report it to the development discord channel."
UpdaterSpriteError = "Sprites.zip does not exist, if this an error please report it to the development discord channel."
